site_name: GCES 1º/2025 - GovHub
repo_url: https://github.com/gces-govhub/gov-hub-wiki                                           |
theme:
  name: 'material'
  palette:
    scheme: 'slate'
    primary: 'indigo'
    accent: 'indigo'
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
  icon:
    logo: material/library
    repo: fontawesome/brands/github


nav:
  - Início: index.md
  - Roadmap:
      Disciplina: roadmap/roadmap-gces.md
  - Papéis de Governança: papeis.md
  - Sprints: sprints/sprints.md
  - Checklist: checklist/checklist.md
